[package]
name = "port-sniffer"
version = "0.1.0"
authors = ["antonio-dipalma <dipalma.antonio98@gmail.com>"]
edition = "2021"

[dependencies]
bpaf = { version = "0.7", features = ["derive", "bright-color"] }
tokio = { version = "1", features = ["full"] }